spring.application.name=desafio
spring.data.mongodb.uri=mongodb+srv://luizeduardolopes2001_db_user:obhD8qCoSaF4Hgc0@cluster0.fsmqcef.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=gerdau_prototipo