spring.application.name=desafio

# Sintaxe para Spring Boot 3.x / 4.x:
spring.mongodb.uri=mongodb+srv://luizeduardolopes2001_db_user:obhD8qCoSaF4Hgc0@cluster0.fsmqcef.mongodb.net/gerdau_prototipo?retryWrites=true&w=majority
spring.mongodb.database=gerdau_prototipo

# manter suporte legado por garantia, manter ambas:
spring.data.mongodb.uri=mongodb+srv://luizeduardolopes2001_db_user:obhD8qCoSaF4Hgc0@cluster0.fsmqcef.mongodb.net/gerdau_prototipo?retryWrites=true&w=majority
spring.data.mongodb.database=gerdau_prototipo