spring.application.name=desafio

# Configuração direta para o time clonar e rodar
spring.mongodb.uri=mongodb+srv://gerdau_mvp_user:gerdaumvp2026@cluster0.fsmqcef.mongodb.net/gerdau_prototipo?retryWrites=true&w=majority
spring.mongodb.database=gerdau_prototipo

# Suporte Spring Data
spring.data.mongodb.uri=${spring.mongodb.uri}
spring.data.mongodb.database=${spring.mongodb.database}